# Generated by Django 5.2.4 on 2025-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', help_text='имя', max_length=75)),
                ('full_text', models.TextField(verbose_name='текст комментария')),
                ('date', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
    ]
