# Generated by Django 5.2.4 on 2025-07-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(help_text='autor', max_length=75)),
                ('song_name', models.CharField(help_text='song_name', max_length=75)),
                ('file', models.FileField(upload_to='uploadsmodel')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
