# Generated by Django 5.2.4 on 2025-07-31 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=75)),
                ('song_name', models.CharField(max_length=75)),
                ('file', models.FileField(upload_to='uploadsmodel', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('my_playlist_img', models.FileField(upload_to='uploadsmodel')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AlterField(
            model_name='uploadsongs',
            name='autor',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='uploadsongs',
            name='file',
            field=models.FileField(upload_to='uploadsmodel', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AlterField(
            model_name='uploadsongs',
            name='song_name',
            field=models.CharField(max_length=75),
        ),
    ]
