# Generated by Django 5.2.4 on 2025-08-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myplaylist_alter_uploadsongs_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myplaylist',
            options={'verbose_name': 'My Playlist Song', 'verbose_name_plural': 'My Playlist Songs'},
        ),
        migrations.RemoveField(
            model_name='myplaylist',
            name='my_playlist_img',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='wishwrld user', help_text='имя', max_length=75),
        ),
    ]
